package com.miaoshaProject.dataobject;

public class OrderAddressStatusDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address_status.id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address_status.order_id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address_status.order_address_id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    private Integer orderAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_address_status.order_status
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    private Integer orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address_status.id
     *
     * @return the value of order_address_status.id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address_status.id
     *
     * @param id the value for order_address_status.id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address_status.order_id
     *
     * @return the value of order_address_status.order_id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address_status.order_id
     *
     * @param orderId the value for order_address_status.order_id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address_status.order_address_id
     *
     * @return the value of order_address_status.order_address_id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public Integer getOrderAddressId() {
        return orderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address_status.order_address_id
     *
     * @param orderAddressId the value for order_address_status.order_address_id
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public void setOrderAddressId(Integer orderAddressId) {
        this.orderAddressId = orderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_address_status.order_status
     *
     * @return the value of order_address_status.order_status
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_address_status.order_status
     *
     * @param orderStatus the value for order_address_status.order_status
     *
     * @mbg.generated Thu May 02 21:52:27 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }
}