package com.miaoshaProject.dataobject;

public class ShopCarDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.shopCar_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    private Integer shopcarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.user_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.item_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.price
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.amount
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.promo_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    private Integer promoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.shopCar_id
     *
     * @return the value of shop_car.shopCar_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public Integer getShopcarId() {
        return shopcarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.shopCar_id
     *
     * @param shopcarId the value for shop_car.shopCar_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public void setShopcarId(Integer shopcarId) {
        this.shopcarId = shopcarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.user_id
     *
     * @return the value of shop_car.user_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.user_id
     *
     * @param userId the value for shop_car.user_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.item_id
     *
     * @return the value of shop_car.item_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.item_id
     *
     * @param itemId the value for shop_car.item_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.price
     *
     * @return the value of shop_car.price
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.price
     *
     * @param price the value for shop_car.price
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.amount
     *
     * @return the value of shop_car.amount
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.amount
     *
     * @param amount the value for shop_car.amount
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.promo_id
     *
     * @return the value of shop_car.promo_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public Integer getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.promo_id
     *
     * @param promoId the value for shop_car.promo_id
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }
}