package com.miaoshaProject.dataobject;

public class UserAddressDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_id
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_detail
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    private String addressDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.zip_code
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.rcvd_name
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    private String rcvdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.rcvd_tel
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    private String rcvdTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_id
     *
     * @return the value of user_address.address_id
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_id
     *
     * @param addressId the value for user_address.address_id
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_detail
     *
     * @return the value of user_address.address_detail
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_detail
     *
     * @param addressDetail the value for user_address.address_detail
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.zip_code
     *
     * @return the value of user_address.zip_code
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.zip_code
     *
     * @param zipCode the value for user_address.zip_code
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.rcvd_name
     *
     * @return the value of user_address.rcvd_name
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public String getRcvdName() {
        return rcvdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.rcvd_name
     *
     * @param rcvdName the value for user_address.rcvd_name
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public void setRcvdName(String rcvdName) {
        this.rcvdName = rcvdName == null ? null : rcvdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.rcvd_tel
     *
     * @return the value of user_address.rcvd_tel
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public String getRcvdTel() {
        return rcvdTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.rcvd_tel
     *
     * @param rcvdTel the value for user_address.rcvd_tel
     *
     * @mbg.generated Tue Apr 23 18:26:14 CST 2019
     */
    public void setRcvdTel(String rcvdTel) {
        this.rcvdTel = rcvdTel == null ? null : rcvdTel.trim();
    }
}