package com.miaoshaProject.dao;

import com.miaoshaProject.dataobject.ShopCarDO;
import com.miaoshaProject.service.model.ShopCarModel;
import org.apache.ibatis.annotations.Param;

public interface ShopCarDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    int deleteByPrimaryKey(Integer shopcarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    int insert(ShopCarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    int insertSelective(ShopCarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    ShopCarDO selectByPrimaryKey(Integer shopcarId);
    ShopCarDO selectByItemIdUserId(Integer userId, Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    int updateByPrimaryKeySelective(ShopCarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbg.generated Tue Apr 16 17:29:07 CST 2019
     */
    int updateByPrimaryKey(ShopCarDO record);

    int increaseAmount(@Param("id")Integer id,@Param("amount") Integer amount);
}